Board/urls.py
from django.conf.urls import url
from . import views

app_name = 'Board'
urlpatterns = [
    url(r'^(?P<section_id>[a-z]+)/$', views.section, name='section'),
    url(r'^$', views.index, name='index'),
]

Image_board/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(regex=r'^admin/', view=admin.site.urls),
    url(regex=r'^board/', view=include('Board.urls')),
    url(regex=r'^', view=include('Board.urls')),
    url(regex=r'^captcha/', view=include('captcha.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Board/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.


class Section(models.Model):
    # a, vg, b, etc
    name_section = models.CharField(max_length=3)

    # tv, video games, music, etc
    description = models.CharField(max_length=25)

    def __str__(self):
        return "%s %s" % (self.name_section, self.description)


class Thread(models.Model):
    class Meta:
        ordering = ['-last_date_pub']
    # League of legends, World of Tanks, Toradora
    name_thread = models.CharField(max_length=30)

    # anonymous
    name_author = models.CharField(max_length=30, default="Anonymous")

    # 31 august 2016
    date_pub = models.DateTimeField()

    last_date_pub = models.DateTimeField()

    # number of original post in the section
    original_post_number = models.IntegerField(default=1)

    # number of posts in this thread
    thread_posts_number = models.IntegerField(default=0)

    # Hello, my name is Karen, I'm from Mexico
    original_post = models.CharField(max_length=1000)

    # the foreign key
    section = models.ForeignKey(Section, on_delete=models.CASCADE, related_name="threads")

    def __str__(self):
        return self.section.name_section + " " + self.name_thread


class Post(models.Model):
    # anonymous 2
    name_author = models.CharField(max_length=30, default="Anonymous")

    # 1 september 2016
    date_pub = models.DateTimeField()

    number_of_image = models.IntegerField(default="0")

    # number of post in the section
    post_number = models.IntegerField(default=1)

    # Hello, Karen, how are you?
    message = models.CharField(max_length=1000)

    # the foreign key
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, related_name="posts_in_thread")

    def __str__(self):
        return self.message + " - " + self.thread.name_thread


class PostCounter(models.Model):
    post_number = models.IntegerField(default=0)
    threads_number = models.IntegerField(default=0)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, related_name="counter")

    def __str__(self):
        strings = self.section.name_section
        return strings + " " + str(self.post_number) + " постов, " + str(self.threads_number) + " тредов"


def user_directory_path(instance, filename):
    return "Media/{0}/{1}/{2}_{3}".format(instance.thread.section.name_section, instance.thread.id,
                                          str(instance.id), filename)


def get_name(instance, filename):
    x, y = filename
    return x


class ImagesOfOriginalPost(models.Model):
    name = models.CharField(max_length=50)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, related_name="op_img")
    image = models.ImageField(upload_to=user_directory_path)
    image_thumbnail = ImageSpecField(source='image',
                                     processors=[ResizeToFill(300, 200)],
                                     format='JPEG',
                                     options={'quality': 80})

    def __str__(self):
        string = " ".join([self.thread.section.name_section, self.thread.name_thread, "1"])
        return string


def user_directory_path_post(instance, filename):
    return "Media/{0}/{1}/{2}_{3}".format(instance.post.thread.section.name_section,
                                          instance.post.thread.id, instance.id,
                                          filename)


class ImagesOfPost(models.Model):

    name = models.CharField(max_length=6, default="image1")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="img")
    image = models.ImageField(upload_to=user_directory_path_post, blank=True)
    image_thumbnail = ImageSpecField(source='image',
                                     processors=[ResizeToFill(300, 200)],
                                     format='JPEG',
                                     options={'quality': 80})

    def __str__(self):
        string = " ".join([self.post.thread.section.name_section, self.post.thread.name_thread,
                           str(self.post.post_number), self.name])
        return string


@receiver(pre_delete, sender=ImagesOfOriginalPost)
def delete_op_post(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)

Board/forms.py
from django.forms import ModelForm, Textarea, HiddenInput
from .models import Thread, Post, ImagesOfPost
from captcha.fields import CaptchaField


class NewThreadForm(ModelForm):

    captcha = CaptchaField()

    class Meta:
        model = Thread

        fields = ('name_thread', 'name_author', 'original_post')
        widgets = {
            'original_post': Textarea(attrs={'cols': 70, 'rows': 7}),


        }
        labels = {
            
            'original_post': "Текст",
            'name_author': "Имя",
            'name_thread': "Тема",

        }


class NewPostForm(ModelForm):

    captcha = CaptchaField()

    class Meta:
        model = Post
        fields = ('name_author', 'message', 'thread')
        widgets = {
            'message': Textarea(attrs={'cols': 70, 'rows': 3}),
            'thread': HiddenInput()
        }
        labels = {
            'name_author': "Имя",
            'message': "Текст",
        }


class NewImageForm(ModelForm):
    class Meta:
        model = ImagesOfPost
        fields = ('image',
                  )
        labels = {'image': 'Картинка',
                  }

Board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Section, PostCounter, ImagesOfOriginalPost, ImagesOfPost
from .forms import NewThreadForm, NewPostForm, NewImageForm
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def section(request, section_id):

    section_list = Section.objects.all
    section = get_object_or_404(Section, name_section=section_id)
    if request.method == "POST" and 'new_thread' in request.POST:
        form = NewThreadForm(request.POST)

        if form.is_valid():
            new_thread = form.save(commit=False)

            new_thread.date_pub = timezone.now()
            new_thread.last_date_pub = new_thread.date_pub

            post_count = get_object_or_404(PostCounter, section=section.id)
            post_count.threads_number += 1
            post_count.post_number += 1
            new_thread.original_post_number = post_count.post_number

            new_thread.thread_number = post_count.threads_number
            new_thread.section = section

            post_count.save()
            new_thread.save()
            image_form = NewImageForm(request.POST, request.FILES)
            if image_form.is_valid() and request.FILES:

                for img in request.FILES.getlist('image'):
                    ImagesOfOriginalPost.objects.create(name=img.name, thread=new_thread, image=img)
            return redirect("/" + section_id)

    elif request.method == "POST" and 'new_post' in request.POST:
        form = NewPostForm(request.POST)

        if form.is_valid():
            new_post = form.save(commit=False)
            post_count = get_object_or_404(PostCounter, section=section.id)

            post_count.post_number += 1

            new_post.date_pub = timezone.now()
            new_post.post_number = post_count.post_number

            this_thread = new_post.thread
            this_thread.last_date_pub = new_post.date_pub
            this_thread.thread_posts_number += 1
            this_thread.save()
            post_count.save()
            new_post.save()

            image_form = NewImageForm(request.POST, request.FILES)
            if image_form.is_valid() and request.FILES:
                for img in request.FILES.getlist('image'):
                    ImagesOfPost.objects.create(name=img.name, post=new_post, image=img)
            return redirect("/" + section_id)

    thread_list_all = section.threads.all()
    paginator = Paginator(thread_list_all, 5)
    page = request.GET.get('page')

    try:
        thread_list = paginator.page(page)
    except PageNotAnInteger:
        thread_list = paginator.page(1)
    except EmptyPage:
        thread_list = paginator.page(paginator.num_pages)

    indexx = paginator.page_range.index(thread_list.number)
    max_index = len(paginator.page_range)
    start_index = indexx - 10 if indexx >= 10 else 0
    end_index = indexx + 10 if indexx <= max_index - 10 else max_index
    page_range = paginator.page_range[start_index:end_index]

    post_list = [x.posts_in_thread.all()
         #        if x.thread_posts_number <= 5 else x.posts_in_thread.all()[x.thread_posts_number-5:]
                 for x in thread_list]

    image_list = [[some_post.img.all() for some_post in thread_l]
                  for thread_l in post_list]

    zip_list = zip(thread_list, post_list, image_list)

    file_form_list = [NewImageForm() for i in range(4)]
    op_img = [NewImageForm() for i in range(4)]

    context = {'section_list': section_list,
               'this_section': section,
               'thread_list': thread_list,
               'post_list': thread_list,
               'zip_list': zip_list,
               'thread_form': NewThreadForm(),
               'post_form': NewPostForm(),
               'image_form': file_form_list,
               'new_thread_image': op_img,
               'page_range': page_range,
               }
    return render(request, 'Board/section.html', context)


def index(request):
    section_list = Section.objects.all
    context = {'section_list': section_list,
               }
    return render(request, 'Board/index.html', context)

Board/templates/Board/base.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static "Board/common-0.6.1320-.css" %}" media="screen">
    <link rel="stylesheet" type="text/css" href="{% static "Board/futaba-0.6.1320-.css" %}" media="screen">
    <link rel="stylesheet" type="text/css" href="{% static "Board/board.css" %}" media="screen">
    <script type="text/javascript" src="{% static "Board/alertthis.js" %}"></script>
</head>
<body>
<div class="main-container">
    <div id="navigation">
        {% include 'Board/nav.html' %}
    </div>
    <div class="threads-container">
    <div class="logo">{% block logo %} {% endblock %}</div>
        {% block content %}
        {% endblock %}
    </div>
</div>


</body>
</html>

Board/templates/Board/form_post_new.html
<form method="POST" class="new_thread_form" enctype="multipart/form-data">{% csrf_token %}
        {{ post_form.as_p }}

        {% for ff in image_form %}
        {{ ff.as_p }}
            {% endfor %}
        <button type="submit" class="save btn btn-default" name="new_post">Save</button>
        <input type="hidden" name="thread" value="{{ thread.id }}">
    </form>

Board/templates/Board/form_thread_new.html
    <form method="POST" class="new_thread_form" enctype="multipart/form-data">{% csrf_token %}
        {{ thread_form.as_p }}
             {% for ff in new_thread_image %}
        {{ ff.as_p }}
            {% endfor %}
        <button type="submit" class="save btn btn-default" name="new_thread">Save</button>
    </form>

Board/templates/Board/index.html
{% extends 'Board/base.html' %}

{% block title %}
Главная страница
{%  endblock %}

{% block logo %}
Вы находитесь на главной странице
{% endblock %}

{% block content %}
<hr>
{% endblock %}

Board/templates/Board/nav.html
<table class="category" border="0" width="100%" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td class="header">Разделы сайта</td>
        </tr>
        <tr>
            <td class="list">
                 {% for section in section_list %}
                      <div>
                        <a href="{% url 'Board:section' section.name_section %}" title="{{ section.name_section }}" target="board">
                               {{ section.name_section }} — {{ section.description }}
                        </a>
		            </div>
                {% endfor %}
            </td>
        </tr>
    </tbody>
</table>

Board/templates/Board/section.html
{% extends 'Board/base.html' %}

{% block title %}
    {{ this_section.description }}
{%  endblock %}

{% block logo %}
    Раздел – {{ this_section.description }}
{% endblock %}

{% block content %}

    <hr>

    {% include 'Board/form_thread_new.html' %}

    <hr>

    {% include 'Board/thread.html' %}




{% endblock %}

Board/templates/Board/thread.html
<!-- one thread -->

{% for thread, post_list, image_list_one_thread in zip_list %}
    <div class="thread">
        <div class="oppost post">
            <!-- the header of a original post -->
            <span class="replytitle"> {{ thread.name_thread }}</span>
            <span class="postername"> {{ thread.name_author }}</span>
            <span class="post_date">{{ thread.date_pub|date:"D d M Y" }}</span>
            <span class="post_date">{{ thread.date_pub|time:"H:i" }}</span>

            <span class="reflink">No. {{ thread.original_post_number }}</span>

            {% for img in thread.op_img.all %}
                    <div class="file">
                        <img class="thumb" src="{{ img.image_thumbnail.url }}" alt="xxx">
                    </div>
            {% endfor %}
            <div class="postbody">
                <div class="message">
                    {{ thread.original_post }}
                    </div>

            </div>
        </div>
        <!-- post for the thread -->
        <div class="comments_table">
        <ul>
            {% for post in post_list %}
                <li><span class="post_author">{{ post.name_author }}</span>
                    <span class="post_date">{{ post.date_pub|date:"D d M Y" }}</span>
                    <span class="post_date">{{ post.date_pub|time:"H:i" }}</span>

                    <span class="post_number">No. {{ post.post_number }}</span> <br>
                    <br>
                    <!-- pictures of some post -->
                    {% for image in post.img.all %}
                        {% if image.image %}

                            <a href="{{ image.image }}">
                                <img src="{{ image.image_thumbnail.url }}" alt=""></a>

                        {% endif %}
                    {% endfor %}
                    <!-- post text -->
                    <div><p class="wrap"> {{ post.message }}</p></div>
                </li>
            {% endfor %}
            <!-- the form for the new post -->
        </ul>
        <li> {% include 'Board/form_post_new.html' %}  </li>
    </div>
{% endfor %}
</ul>
</div>

<div class="pagination">
    <span class="step-links">
     <!--   {% if thread_list.has_previous %}
          <a href="?page={{ thread_list.previous_page_number }}">назад</a>
        {% endif %}

        <span class="current">
            {{ thread_list.number }} из {{ thread_list.paginator.num_pages }}.
        </span>

        {% if thread_list.has_next %}
           <a href="?page={{ thread_list.next_page_number }}">вперед</a>
       {% endif %} -->

        {% if thread_list.has_previous %}
            <a class="prev-btn-btn-info" href="?page={{ thread_list.previous_page_number }}">Назад</a>
        {% endif %}
        {% if thread_list.has_next %}
            <a class="next-btn-btn-info" href="?page={{ thread_list.next_page_number }}">Вперед</a>
        {% endif %}
        <div class="pages">

        {% for pg in page_range %}
            {% if thread_list.number == pg %}
                <a href="?page={{ pg }}" class="page-current">-{{ pg }}-</a></li>
            {% else %}
                <a href="?page={{ pg }}" class="page-not-current">{{ pg }}</a></li>
            {% endif %}
        {% endfor %}

    </div>


    </span>
</div>
<hr>